import type { MDXComponents } from "mdx/types";
import defaultMdxComponents from "fumadocs-ui/mdx";
import { Callout } from "@/components/mdx/Callout";
import { FeatureCard } from "@/components/mdx/FeatureCard";
import { Step, Steps } from "@/components/mdx/Step";
import { Kbd } from "@/components/mdx/KeyboardShortcut";
import { VoicePipelineDiagram } from "@/components/mdx/PipelineDiagram";
import { InterviewTypeCard } from "@/components/mdx/InterviewTypeCard";
import { StatusIndicator } from "@/components/mdx/StatusIndicator";
import {
  Mic,
  Code2,
  Waypoints,
  Phone,
  Dumbbell,
  BarChart3,
  Brain,
  Zap,
  Target,
  Flame,
  Trophy,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Search,
  Shuffle,
  Volume2,
  MessageSquare,
  Shield,
  FileCode,
  Sparkles,
  Terminal,
  Keyboard,
  Settings,
  User,
  Lock,
  Globe,
  Bell,
  Play,
  Star,
  BookOpen,
  FileText,
  History,
  TrendingUp,
  Calendar,
  Layers,
  Database,
  GitBranch,
  Pencil,
  Palette,
  Command,
  LayoutDashboard,
  CircleHelp,
  Briefcase,
  Building2,
  ListChecks,
  Gauge,
  Timer,
  Award,
  Bug,
  ScrollText,
  MessagesSquare,
  Headphones,
  Activity,
  Monitor,
  MousePointer,
  Wifi,
} from "lucide-react";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    // Custom components
    Callout,
    FeatureCard,
    Step,
    Steps,
    Kbd,
    VoicePipelineDiagram,
    InterviewTypeCard,
    StatusIndicator,
    // Lucide icons — usable in MDX as <Mic />, <Code2 />, etc.
    Mic,
    Code2,
    Waypoints,
    Phone,
    Dumbbell,
    BarChart3,
    Brain,
    Zap,
    Target,
    Flame,
    Trophy,
    Clock,
    CheckCircle2,
    AlertTriangle,
    Lightbulb,
    Search,
    Shuffle,
    Volume2,
    MessageSquare,
    Shield,
    FileCode,
    Sparkles,
    Terminal,
    Keyboard,
    Settings,
    User,
    Lock,
    Globe,
    Bell,
    Play,
    Star,
    BookOpen,
    FileText,
    History,
    TrendingUp,
    Calendar,
    Layers,
    Database,
    GitBranch,
    Pencil,
    Palette,
    Command,
    LayoutDashboard,
    CircleHelp,
    Briefcase,
    Building2,
    ListChecks,
    Gauge,
    Timer,
    Award,
    Bug,
    ScrollText,
    MessagesSquare,
    Headphones,
    Activity,
    Monitor,
    MousePointer,
    Wifi,
    ...components,
  };
}
